export default function Footer() {
  const year = new Date().getFullYear();
  return (
    <footer className="border-t border-neutral-300 mt-16">
      <div className="max-w-7xl mx-auto px-4 py-10">
        <div className="flex flex-col md:flex-row items-center justify-between gap-4">
          <div>
            <h3 className="font-headline text-2xl">The Signal</h3>
            <p className="text-xs text-neutral-500 mt-1">
              AI-powered impartial news aggregation
            </p>
          </div>
          <div className="text-xs text-neutral-400 text-center md:text-right">
            <p>
              Articles are generated by AI from multiple news sources.
            </p>
            <p className="mt-1">
              &copy; {year} The Signal. For informational purposes only.
            </p>
          </div>
        </div>
      </div>
    </footer>
  );
}
