import { notFound } from "next/navigation";
import Link from "next/link";
import { getArticleBySlug, getArticleById, getRelatedArticles } from "@/lib/articles";
import { CATEGORIES } from "@/lib/types";
import ArticleCard from "@/components/ArticleCard";
import ArticleAudioPlayer from "@/components/ArticleAudioPlayer";
import ArticleFeedback from "@/components/ArticleFeedback";

export async function generateMetadata({ params }: { params: { id: string } }) {
  const article = await getArticleBySlug(params.id) || await getArticleById(params.id);
  if (!article) return { title: "Not Found — The Signal" };
  return {
    title: `${article.headline} — The Signal`,
    description: article.summary,
  };
}

export default async function ArticlePage({ params }: { params: { id: string } }) {
  // Try slug first, then id (for backwards compat with mock data)
  const article = await getArticleBySlug(params.id) || await getArticleById(params.id);
  if (!article) notFound();

  const categoryInfo = CATEGORIES.find((c) => c.slug === article.category);
  const related = await getRelatedArticles(article);

  const formattedTime = new Date(article.timestamp).toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
    timeZone: "Australia/Sydney",
  });

  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      {/* Breadcrumb */}
      <nav className="text-xs text-neutral-400 font-sans mb-6">
        <Link href="/" className="hover:text-signal-red">
          Home
        </Link>
        <span className="mx-2">/</span>
        <Link
          href={`/category/${article.category}`}
          className="hover:text-signal-red"
        >
          {categoryInfo?.label}
        </Link>
        <span className="mx-2">/</span>
        <span className="text-neutral-600">Article</span>
      </nav>

      {/* Article Header */}
      <header className="mb-8">
        <h1 className="font-headline text-4xl md:text-5xl lg:text-[3.25rem] font-bold leading-tight mb-4">
          {article.headline}
        </h1>
        <p className="text-lg text-neutral-600 leading-relaxed mb-4">
          {article.summary}
        </p>
        <div className="flex items-center gap-4 text-xs text-neutral-400 font-sans border-t border-b border-neutral-200 py-3">
          <time>{formattedTime}</time>
          <span className="w-1 h-1 bg-neutral-300 rounded-full" />
          <Link
            href={`/category/${article.category}`}
            className="uppercase tracking-widest hover:text-signal-red"
          >
            {categoryInfo?.label}
          </Link>
          <span className="w-1 h-1 bg-neutral-300 rounded-full" />
          <span>The Signal Staff</span>
        </div>
      </header>

      {/* Audio Player */}
      <ArticleAudioPlayer headline={article.headline} body={article.body} />

      {/* Article Body */}
      <div className="mb-12">
        {article.body.split("\n\n").map((paragraph, i) => (
          <p
            key={i}
            className={`text-neutral-800 leading-[1.85] mb-5 text-[17px] ${
              i === 0 ? "drop-cap" : ""
            }`}
          >
            {paragraph}
          </p>
        ))}
      </div>

      {/* Sources */}
      {article.sources.length > 0 && (
        <div className="border-t border-neutral-200 pt-6 mb-12">
          <h4 className="text-xs text-neutral-400 uppercase tracking-widest font-sans mb-2">
            Sources
          </h4>
          <div className="flex flex-wrap gap-2">
            {article.sources.map((source) => (
              <span
                key={source}
                className="text-sm text-neutral-600 bg-neutral-100 px-3 py-1 rounded-full"
              >
                {source}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Reader Feedback */}
      <ArticleFeedback articleId={article.id} />

      {/* Impartiality Notice */}
      <div className="bg-neutral-50 border border-neutral-200 rounded px-5 py-4 mb-12">
        <p className="text-xs text-neutral-500 font-sans leading-relaxed">
          <span className="font-semibold uppercase tracking-wider">Editorial Note:</span>{" "}
          This article was generated by AI from multiple news sources. The Signal aims to
          present factual, balanced reporting by synthesizing information from diverse
          outlets. Readers are encouraged to consult original sources for additional context.
        </p>
      </div>

      {/* Related Articles */}
      {related.length > 0 && (
        <section className="border-t border-neutral-300 pt-8">
          <h3 className="font-headline text-2xl font-bold mb-6">
            More in {categoryInfo?.label}
          </h3>
          <div className="grid md:grid-cols-3 gap-x-8 gap-y-6">
            {related.map((a) => (
              <ArticleCard key={a.id} article={a} />
            ))}
          </div>
        </section>
      )}
    </div>
  );
}
